apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "network-ups-tools.fullname" . }}
  labels:
    {{- include "network-ups-tools.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "network-ups-tools.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "network-ups-tools.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "network-ups-tools.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      volumes:
        - name: udev
          hostPath:
            path: /run/udev
        - name: configuration-secret
          secret:
            secretName: {{ include "network-ups-tools.fullname" . }}-configuration
      {{- if .Values.usb.enabled }}
        - name: usb
          hostPath:
            path: {{ .Values.usb.hostPath }}
      {{- end }}
      {{- if .Values.debug.initContainer.enabled }}
      initContainers:
        - command:
          - sh
          - -c
          - sleep infinity;
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: init-debug
          volumeMounts:
            - name: configuration-secret
              mountPath: "/etc/nut"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: udev
              mountPath: /run/udev
              readOnly: true
            - name: configuration-secret
              mountPath: "/etc/nut"
          {{- if .Values.usb.enabled }}
            - name: usb
              mountPath: {{ .Values.usb.hostPath }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.debug.container.enabled }}
          command:
          - sh
          - -c
          - sleep infinity;
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
