apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mqtt
  namespace: mqtt
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - mqtt
  routes:
    - match: HostSNI(`*`)
      priority: 10
      services:
        - name: mqtt-mosquitto
          port: 1883
  tls:
    passthrough: false
    secretName: evercraft-fr-tls
