{{- if .Values.traefik.enabled }}
{{- $fullName := include "teamspeak.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ $fullName }}-voice
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.traefik.udp.voice.entryPoint }}
  routes:
    - services:
        - name: {{ $fullName }}
          port: {{ .Values.service.voice.port }}
{{- end }}




