{{- if .Values.traefik.enabled }}
{{- $fullName := include "teamspeak.fullname" . -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-serverquery
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.traefik.tcp.serverQuery.entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.serverQuery.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-serverquery-ssh
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.traefik.tcp.serverQuerySsh.entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.serverQuerySsh.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-filetransfer
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
  {{- with .Values.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.traefik.tcp.fileTransfer.entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.fileTransfer.port }}
{{- end }}










