apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.voice.port }}
      targetPort: voice
      protocol: UDP
      name: voice
      {{- if and (eq .Values.service.type "NodePort") .Values.service.voice.nodePort }}
      nodePort: {{ .Values.service.voice.nodePort }}
      {{- end }}
    - port: {{ .Values.service.serverQuery.port }}
      targetPort: serverquery
      protocol: TCP
      name: serverquery
      {{- if and (eq .Values.service.type "NodePort") .Values.service.serverQuery.nodePort }}
      nodePort: {{ .Values.service.serverQuery.nodePort }}
      {{- end }}
    - port: {{ .Values.service.serverQuerySsh.port }}
      targetPort: serverquery-ssh
      protocol: TCP
      name: serverquery-ssh
      {{- if and (eq .Values.service.type "NodePort") .Values.service.serverQuerySsh.nodePort }}
      nodePort: {{ .Values.service.serverQuerySsh.nodePort }}
      {{- end }}
    - port: {{ .Values.service.fileTransfer.port }}
      targetPort: filetransfer
      protocol: TCP
      name: filetransfer
      {{- if and (eq .Values.service.type "NodePort") .Values.service.fileTransfer.nodePort }}
      nodePort: {{ .Values.service.fileTransfer.nodePort }}
      {{- end }}
  selector:
    {{- include "teamspeak.selectorLabels" . | nindent 4 }}








